version: '3.9'
services:
  truyentranh-cms:
    build:
      args:
        user: truyentranh
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: truyentranh-cms
    container_name: truyentranh-cms
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - truyentranh
  nginx:
    image: nginx:1.17-alpine
    container_name: truyentranh-nginx
    restart: unless-stopped
    ports:
      - 4000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - truyentranh

  postgres:
    container_name: truyentranh-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - truyentranh
    restart: unless-stopped
  redis:
    container_name: truyentranh-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data/redis
    networks:
      - truyentranh
    restart: unless-stopped
      
networks:
  truyentranh:
    driver: bridge
volumes:
    postgres:
    redis:
