<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->page_title; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="<?php echo SITE_URL ?>public/icons/small-devilchan.png"  sizes="16x16">
    <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL; ?>public/css/reset.css">
    <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL; ?>public/css/admin.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300&display=swap" rel="stylesheet"> 
</head>
<body style="background: #ebebeb">