<?php
	
	$this->page_title = "Đổi mật khẩu - " . SITE_NAME;
	include VIEW . "user/wall/header.phtml";
?>
	<div class="content">
		<div class="row content-inner clearfix">
			<?php include  VIEW . "user/wall/sidebar.phtml" ?>
			<div class="user-form">
				<div class="box-title">
					<h2 >Đổi mật khẩu <i class="fa fa-angle-right"></i></h2>
				</div>
				<div class="u-input-group">
					<label>Mật khậu hiện tại : </label>
					<input type="password" id="current_password" name="current_password">
				</div>
				<div class="u-input-group">
					<label>Mật khẩu mới : </label>
					<input type="password" id="new_password" name="new_password">
				</div>
				<div class="u-input-group">
					<label>Nhập lại mật khẩu mới : </label>
					<input type="password" id="confirm_password" name="r_new_password">
				</div>
				<div class="u-input-group u-btn">
					<button class="btn" id="change-password">Update</button>
				</div>
			</div>
		</div>
	</div>
<?php
	include VIEW . "main/footer.phtml";
?>