<?php

    $d = $this->getData();

    $favorites = @$d["favorites"];
    $d["pagi"]["url"] = "/member/favorites";
    $page = @$d["page"];
    
    /////////////////////////////////////////////////////////
    $page_title = "Truyện đã thích";

    if($page > 1){
        $page_title = $page_title . " | Page " . $page;
    }

    $this->page_title = $page_title . " - " . SITE_NAME;

    include VIEW . "user/wall/header.phtml";
?>
    <div class="content">
        <div class="row content-inner clearfix">
            <?php include  VIEW . "user/wall/sidebar.phtml" ?>
            <div class="user-form">
                <div class="box-title">
                    <h2><?= $page_title ?> <i class="fa fa-angle-right"></i></h2>
                </div>
                <?php

                    if($favorites):

                        echo "<div>";

                        foreach ($favorites as $favorite) :

                            $manga_id = $favorite["manga_id"];
                            $manga_name = $favorite["manga_name"];

                            $cover_img = SITE_URL . "img/{$manga_id}/{$favorite['manga_cover_img']}";
                            $manga_url = "/manga/" . url_name_replace($manga_name) . "-" . $manga_id;

                ?>
                <div class="u-fav-item clearfix">
                    <div class="u-img-holder">
                        <a href="<?= $manga_url ?>" title="<?= $manga_name ?>"><img src="<?= $cover_img ?>"></a>
                    </div>
                    <div class="u-manga-title"><a title="<?= $manga_name ?>" href="<?= $manga_url ?>"><?= $manga_name ?></a></div>
                    <div class="u-fav-btn">
                        <a href="javascript:void(0)" data-manga-id="<?= $manga_id ?>" title="Unfavorite">
                            <img src="<?= TH_PUBLIC . "/icons/x.svg" ?>"><span>Unfavorite</span>
                        </a>
                    </div>
                </div>
                <?php 
                        endforeach;
                        echo "</div>";
                        echo html::pagi(html::pagi_render($d["pagi"]));

                    else:

                        echo "Chưa thích truyện nào.";

                    endif
                ?>
            </div>
        </div>
    </div>
<?php
    include VIEW . "main/footer.phtml";
?>